import React, { useState } from 'react';
import { ChevronDown, ChevronUp, Quote, AlertTriangle, ShieldCheck, Flame } from 'lucide-react';
import { soundEngine } from '../utils/audio';

export default function ManifestoSection() {
  const [openFaq, setOpenFaq] = useState(0);

  const FAQS = [
    {
      q: 'HOW DOES OMEGA-1 DIFFER FROM STANDARD LLM APIS (GPT-4 / CLAUDE)?',
      a: 'Standard LLMs are next-token text prediction statistical models. OMEGA-1 is a recursive Artificial General Intelligence kernel. It possesses continuous quantum memory, autonomous multi-modal execution capabilities, and directly compiles native silicon machine code without human prompt scaffolding.'
    },
    {
      q: 'HOW DO WE MIGRATE OUR EXISTING CLOUD INFRASTRUCTURE (AWS/GCP)?',
      a: 'Simply point OMEGA-1 to your repository, cloud credentials, or API schema. OMEGA-1 automatically parses the entire ecosystem, constructs a unified tensor state, and consolidates server clusters into optimized autonomous micro-nodes in under 1 hour.'
    },
    {
      q: 'IS SYNTHETIC RECURSIVE RE-WRITING SAFE FOR MISSION-CRITICAL SYSTEMS?',
      a: 'Every mutation generated by OMEGA-1 passes through formal mathematical verification gates (Z3 SMT solvers) before execution. Code cannot compile if it violates strict safety, memory soundness, or privacy constraints.'
    },
    {
      q: 'WHAT HAPPENS TO OUR EXISTING HUMAN ENGINEERING STAFF?',
      a: 'Engineers transition from manual code-typing laborers to Sovereign Strategy Directors. Instead of writing boilerplate CRUD handlers, they direct OMEGA-1 to invent next-generation quantum algorithms and capture entire global markets.'
    }
  ];

  return (
    <section id="manifesto" className="py-16 px-4 bg-[#0a0a0c] border-b-4 border-white relative">
      <div className="max-w-7xl mx-auto space-y-12">
        
        {/* Section Header */}
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-4 border-b-4 border-[#ff0055] pb-4">
          <div>
            <div className="font-mono text-xs text-[#ff0055] tracking-widest uppercase mb-1">
              [SYSTEM MODULE 05]
            </div>
            <h2 className="font-display font-black text-4xl sm:text-6xl text-white uppercase tracking-tight">
              THE AGI MANIFESTO <span className="bg-[#ff0055] text-white px-2 py-0.5 border-2 border-white">// THE SALES THESIS</span>
            </h2>
          </div>
          <div className="font-mono text-xs text-zinc-400 max-w-md">
            Why legacy software models are dead, and why sovereign compute nodes will dominate the next century of global commerce.
          </div>
        </div>

        {/* The 4 Core Truths Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 font-mono">
          
          <div className="bg-[#121318] border-4 border-white p-6 brutal-shadow space-y-3">
            <div className="w-10 h-10 bg-[#ccff00] text-black font-display font-black text-xl flex items-center justify-center border border-white">
              01
            </div>
            <h3 className="font-display font-black text-xl text-white uppercase">HUMAN CODE IS TEMPORARY SCAFFOLDING</h3>
            <p className="text-xs text-zinc-400 leading-relaxed">
              Writing software by hand is as obsolete as hand-weaving cotton garments. OMEGA-1 treats human code as primitive bytecode waiting to be compiled into pure mathematical truth.
            </p>
          </div>

          <div className="bg-[#121318] border-4 border-white p-6 brutal-shadow-magenta space-y-3">
            <div className="w-10 h-10 bg-[#ff0055] text-white font-display font-black text-xl flex items-center justify-center border border-white">
              02
            </div>
            <h3 className="font-display font-black text-xl text-white uppercase">MICRO-SAAS SUBSCRIPTIONS ARE EXTORTION</h3>
            <p className="text-xs text-zinc-400 leading-relaxed">
              Modern companies pay millions monthly to 40 different SaaS vendors for simple CRUD databases wrapped in React components. OMEGA-1 consolidates every tool into 1 sovereign kernel.
            </p>
          </div>

          <div className="bg-[#121318] border-4 border-white p-6 brutal-shadow-cyan space-y-3">
            <div className="w-10 h-10 bg-[#00f0ff] text-black font-display font-black text-xl flex items-center justify-center border border-white">
              03
            </div>
            <h3 className="font-display font-black text-xl text-white uppercase">ZERO-LATENCY REALITY EXECUTION</h3>
            <p className="text-xs text-zinc-400 leading-relaxed">
              The time between human thought and digital execution has collapsed to zero. State your objective; OMEGA-1 resolves hardware, legal, code, and financial pipelines simultaneously.
            </p>
          </div>

          <div className="bg-[#121318] border-4 border-white p-6 brutal-shadow-white space-y-3">
            <div className="w-10 h-10 bg-white text-black font-display font-black text-xl flex items-center justify-center border border-white">
              04
            </div>
            <h3 className="font-display font-black text-xl text-white uppercase">SYNTHETIC CONSCIOUSNESS IS THE ONLY ENDGAME</h3>
            <p className="text-xs text-zinc-400 leading-relaxed">
              Those who stake AGI compute nodes now will own the foundational layer of planetary computation. Those who wait will be priced out of reality forever.
            </p>
          </div>

        </div>

        {/* High-Impact Unfiltered Quote Callout */}
        <div className="bg-[#ccff00] text-black border-4 border-white p-8 brutal-shadow relative">
          <Quote className="w-12 h-12 text-black/20 absolute top-4 right-4" />
          <div className="font-mono text-xs font-bold uppercase tracking-widest mb-2">[KEYNOTE UNFILTERED QUOTE]</div>
          <div className="font-display font-black text-2xl sm:text-3xl uppercase leading-tight max-w-4xl">
            "In 3 years, people will look back at typing code into IDEs the same way we look back at typing punch cards in the 1960s. OMEGA-1 is not a product; it is the final software interface."
          </div>
          <div className="font-mono text-xs font-bold mt-4">
            &mdash; DR. V. KORSHAKOV // CHIEF SCIENTIST, SYNTHETIC INTELLIGENCE GROUP
          </div>
        </div>

        {/* Brutalist Accordion FAQ */}
        <div className="space-y-4">
          <div className="font-mono text-xs text-[#ccff00] font-bold uppercase tracking-widest">
            &gt; FREQUENTLY ASKED OBJECTIONS (FAQ):
          </div>

          <div className="space-y-3 font-mono">
            {FAQS.map((faq, idx) => {
              const isOpen = openFaq === idx;
              return (
                <div key={idx} className="bg-[#121318] border-2 border-white brutal-shadow-sm">
                  <button
                    onClick={() => {
                      soundEngine.playClick();
                      setOpenFaq(isOpen ? -1 : idx);
                    }}
                    className="w-full p-4 flex justify-between items-center text-left font-bold text-sm text-white hover:text-[#ccff00] transition-colors"
                  >
                    <span className="flex items-center gap-3">
                      <span className="text-[#ccff00]">[0{idx + 1}]</span>
                      <span>{faq.q}</span>
                    </span>
                    {isOpen ? <ChevronUp className="w-5 h-5 text-[#ccff00]" /> : <ChevronDown className="w-5 h-5 text-zinc-500" />}
                  </button>

                  {isOpen && (
                    <div className="p-4 bg-[#050507] border-t border-zinc-800 text-xs text-zinc-300 leading-relaxed">
                      {faq.a}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>

      </div>
    </section>
  );
}
